name: CI/CD
on:
  - push
  - pull_request
env:
  FORCE_COLOR: 3
jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npx nr build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nr release
